apiVersion: v1
kind: Service
metadata:
  name: hpa-eval-fixed-svc
  namespace: hpa-eval
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-eval-hpa-svc
  namespace: hpa-eval
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30081
